---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/codequokka/argocd-poc.git
    targetRevision: setup-helmfile-plugin
    # targetRevision: main
    path: helmfile
    plugin: {}
  destination:
    server: https://kubernetes.default.svc
    # namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  # parameters:
  #   - name: ENV_NAME
  #     value: poc
