---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/codequokka/argocd-poc.gi
    targetRevision: app-of-apps-test
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

# argocd app create apps \
#     --dest-namespace argocd \
#     --dest-server https://kubernetes.default.svc \
#     --repo https://github.com/argoproj/argocd-example-apps.git \
#     --path apps
# argocd app sync apps
